name: CI Pipeline (Tự động Test)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request: 
    branches: [ "main", "dev" ]

jobs:
  test-java-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Lấy code từ Github
      uses: actions/checkout@v3
      
    - name: Cài đặt Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Chạy Test cho Document Service
      working-directory: ./services/document-service
      run: mvn clean test
      
    - name: Chạy Test cho User Service
      working-directory: ./services/user-service
      run: mvn clean test

  test-python-ai:
    runs-on: ubuntu-latest
    steps:
    - name: Lấy code từ Github
      uses: actions/checkout@v3
      
    - name: Cài đặt Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Cài đặt thư viện Python
      working-directory: ./services/recommendation-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Chạy Pytest & Đo Code Coverage
      working-directory: ./services/recommendation-service
      run: pytest --cov=.

  test-frontend-ui:
    runs-on: ubuntu-latest
    steps:
    - name: Lấy code từ Github
      uses: actions/checkout@v3
      
    - name: Cài đặt NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Cài đặt thư viện Frontend
      working-directory: ./frontend
      run: npm install
        
    - name: Chạy Unit Test Frontend (Nếu có)
      working-directory: ./frontend
      run: npm run test || echo "Chưa có file test nào, tạm bỏ qua!"
